config/routes.rb
Rails.application.routes.draw do
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "tasks#index"

  namespace :admin do
    resources :users
  end
  root "tasks#index"
  resources :tasks do
    # :confirmはパスか 
    post :confirm, action: :confirm_new, on: :new
    post :import, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
 validates :name, presence: true 
 validate :validate_name_not_inclueding_column
 validate :validate_long_name
 has_one_attached :image

 scope :recent, -> { order(created_at: :desc) }

 belongs_to :user

  def self.csv_attributes
    # カラムの出力
    ["name", "description", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map{|attr| task.send(attr)}
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      task = new
      task.attributes = row.to_hash.slice(*csv_attributes)
      task.save!
    end
  end

  def validate_name_not_inclueding_column
    errors.add(:name, "にカンマを含める事はできません") if name&.include?(',')
  end

  def validate_long_name
    errors.add(:name, "名前が長すぎます") if name.length > 5
  end

  def self.ransakable_attributes(auth_object = nil)
    %w[name created_at description]
  end
  def self.ransakable_associations(auth_object = nil)
    []
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, UserUploader
  has_secure_password
  has_many :tasks
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin, except: [:new, :create]
  skip_before_action :login_required, only: [:new,:create]
  skip_before_action :verify_authenticity_token


  def index
    @users = User.all    
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
  
    if @user.save!
      session[:user_id] = @user.id 
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    # if 
    #   redirect_to admin_user_path(@user)
    # else
    #   render :new
    # end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image,:admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to login_path unless current_user.admin? 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user || User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required


    redirect_to login_path unless current_user 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
 
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def session_params
    params.require(:session).permit(:email,:password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit]
  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page]).per(10)

  end

  def import
    current_user.tasks.import(params[:file])
    redirect_to tasks_url
  end

  def show
  end

  def new
    @task = Task.new
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def create
    @task = Task.new(task_params.merge(user_id: current_user.id))
    
    if params[:back].present?
      render :new
      return
    end
    if @task.save
      TaskMailer.creation_email(@task).deliver_now
      SampleJob.perform_later
      flash[:notice] = "タスク#{@task.name}を登録しました"
      redirect_to tasks_url
    else
      render :new
    end
    
  end

  def edit
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update!(task_params)
    flash[:notice] = "タスクを更新しました"
    redirect_to tasks_url
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy
    flash[:notice] = "削除完了しました"
    redirect_to tasks_url
  end

  private
  def task_params
    params.require(:task).permit(:name,:description, :image)
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/edit.html.slim
h1 ユーザー編集

= form_with model: [:admin, @user], local: true do |f|
  .from-group
    = f.label :name, "名前"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email, "メールアドレス"
    = f.text_field :email, class: "form-control"
  .form-check
    = f.label :email, "メールアドレス"
      = f.check_box :email, class:"form-check-input"
        | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, 'パスワード'
    = f.password_field :password_confirmation, class: "form-control"
  = f.submit '登録する', class:"btn btn-primary"

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to "新規登録", new_admin_user_path, class: "btn btn-primary"

.md-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:name)
      th = User.human_attribute_name(:email)
      th = User.human_attribute_name(:admin)
      th = User.human_attribute_name(:created_at)
      th = User.human_attribute_name(:updated_at)
  tbody
    - @users.each do |user|
      tr
        td = link_to user.name,[:admin, user]
        td = user.email
        td = user.admin? ? 'あり' : 'なし'
        td = user.created_at
        td = user.updated_at
        td
          = link_to "編集", edit_admin_user_url(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { donfirm: "ユーザー#{user.name}を削除しますか？"}, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

= form_for [:admin, @user] do |f|
  .from-group
    = f.label :name, "名前"
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :email, "メールアドレス"
    = f.email_field :email, class: "form-control"
  .form-check
    = f.label :email, "メールアドレス"
      = f.check_box :email, class:"form-check-input"
        | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, 'パスワード'
    = f.password_field :password_confirmation, class: "form-control"
  = f.submit '登録する', class:"btn btn-primary"

app/views/admin/users/show.html.slim
= react_component("users/User", {user: @user})

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TaskForBook
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand TaskLeaf
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item = link_to "タスク一覧", tasks_path, class: "nav-link"
          li.nav-item = link_to "ユーザー一覧", admin_users_path, class: "nav-link"
          li.nav-item = link_to "マイページ", "/admin/users/#{current_user.id}", class: "nav-link"
          li.nav-item = link_to "ログアウト", logout_path, method: :delete, class: "nav-link" 
        - else
          li.nav-item = link_to "会員登録", new_admin_user_path, class: "nav-link"
          li.nav-item = link_to "ログイン", login_path, class: "nav-link"
    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice

      script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-108537919-1" 
      javascript:
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-108537919-1');
      = yield

app/views/tasks/confirm_new.html.slim
h1 登録画面の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th= Task.human_attribute_name(:name)
        td= @task.name
        = f.hidden_field :name
      tr
        th=Task.human_attribute_name(:description)
        td= simple_format(@task.description)
        = f.hidden_field :description
      tr
        th=Task.human_attribute_name(:description)
        td= image_tag @task.image if @task.image.attached?
        = f.hidden_field :image
  = f.submit '戻る', name: 'back', class: "btn btn-secondary mr-3"
  = f.submit "登録", class:"btn btn-primary"       

app/views/tasks/edit.html.slim
h1  タスク

.nav.justify-content-end
  = link_to "一覧", tasks_path, class: "nav-link"

= form_with model: @task, local: true do |f|
  .form_group
    = f.label :name
    = f.text_field :name, class: "form-control", id: "task_name"
  .form_group
    = f.label :description
    = f.text_field :description, class: "form-control", id: "task_description"
  = f.submit nil, class:"btn btn-primary"
        

app/views/tasks/index.html.slim
h1 タスク一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont,'名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      =f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq,'登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      =f.search_field :created_at_gteq, class: 'form-control'
  .form-group.row
    = f.label :description_cont,'詳細内容', class: 'col-sm-2 col-form-label'
    .col-sm-10
      =f.search_field :description_cont, class: 'form-control'
  .form-group
    = f.submit class: ' btn btn-outline-primary'
= link_to "新規登録", new_task_path , class: "btn btn-primary"
.mb-3
  = paginate @tasks
  = page_entries_info @tasks
table.table.table-hover
  thead.thead-default
    tr
      th= sort_link(@q, :name, [:name, "created_at desc"])
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:created_at)
  tbody
    - @tasks.each do |task|
      tr
        td= link_to task.name, task 
        td= task.created_at
        td 
          = link_to "編集", edit_task_path(task), clas: 'btn btn-primary mr-3'
          = link_to "削除", task, method: :delete , data: {confirm: "タスク#{task.name}を削除しますか?"},clas: 'btn btn-primary mr-3'
= link_to 'エクスポート', tasks_path(format: :csv), class: "btn btn-primary mb-3"
= form_tag import_tasks_path, multipart: true, class: 'mb-3' do 
  = file_field_tag :file
  = submit_tag "インポート", class: "btn btn-primary"

app/views/tasks/new.html.slim
h1 タスク登録

.nab.justify-content-end
  = link_to "一覧", tasks_path,class:"nav-link"

- if @task.errors.present?
  ul#error_explanation
    - @task.errors.full_messages.each do |message|
      li.alert.alert-danger = message

= form_with(model: @task, url: "/tasks", local: true) do |f|
  .form_group
    = f.label :name
    = f.text_field :name, class: "form-control", id: "task_name"
  .form_group
    = f.label :description
    = f.text_field :description, class: "form-control", id: "task_description"
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class:"btn btn-primary"
        

app/views/tasks/show.html.slim
h1 タスク詳細

.nav.jstify-contend-end
  = link_to "一覧", tasks_path, class:"nav-link"


table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description), {},sanitize: false,wrapper_tag: "div"), html: {target: '_blank'})
    tr
      th= Task.human_attribute_name(:image)
      td= image_tag @task.image if @task.image.attached?
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at